In [10]:
import pandas as pd

# Existing data
data = [
    ['Cash & cash equivalents', '159,727,124', '196,276,818'],
    ['Loans to members - net', '2,006,007,543', '1,812,554,760'],
    ['Investments - net', '436,009,396', '442,691,070'],
    ['Share insurance deposits', '22,404,491', '21,088,087'],
    ['Property & equipment - net', '72,865,806', '73,988,903'],
    ['Other assets', '67,157,515', '62,727,010'],
    ['Total Assets', '2,764,171,874', '2,609,326,648'],
    ['Members\' shares', '2,367,703,123', '2,304,469,074'],
    ['Accrued expenses and other liabilities', '22,178,627', '8,813,915'],
    ['Borrowed funds', '152,500,000', '47,500,000'],
    ['Total Liabilities', '2,542,381,750', '2,360,782,989'],
    ['Retained earnings', '273,256,010', '250,297,815'],
    ['Accumulated other comprehensive income (loss)', '-51,465,887', '-1,754,156'],
    ['Total Members’ Equity', '221,790,124', '248,543,659'],
    ['Total Liabilities and Members’ Equity', '2,764,171,874', '2,609,326,648']
]

# Additional data
additional_data = [
    ['Interest on loans', '82,655,221', '68,828,526'],
    ['Interest on investments and cash equivalents', '10,668,145', '7,253,814'],
    ['Total Interest Income', '93,323,366', '76,082,340'],
    ["Dividends on members' shares", '-3,089,566', '-2,986,948'],
    ['Interest on borrowed funds', '-2,177,786', '-402,858'],
    ['Total Interest Expense', '-5,267,352', '-3,389,806'],
    ['Net Interest Income', '88,056,013', '72,692,534'],
    ['Provision for Loan Losses', '8,230,118', '1,573,648'],
    ['Net Interest Income After Provision', '79,825,895', '71,118,886'],
    ['Service charges and other fees', '12,386,604', '11,937,739'],
    ['Other non-interest income', '21,115,956', '20,000,467'],
    ['Gain (loss) on sales of property and equipment', '5,449,153', '967,057'],
    ['Gain (loss) on sale of investments', '-5,758,275', '990,818'],
    ['Total Non-Interest Income', '33,193,438', '33,896,081'],
    ['Salaries and benefits', '-44,500,571', '-40,396,930'],
    ['Operations', '-39,868,778', '-33,713,380'],
    ['Occupancy', '-5,691,789', '-5,276,312'],
    ['Total General and Administrative Expenses', '-90,061,138', '-79,386,622'],
]

# Create DataFrames for the existing data and additional data
df_assets = pd.DataFrame(data, columns=['Category', '2022', '2021'])
df_additional = pd.DataFrame(additional_data, columns=['Category', '2022', '2021'])

# Concatenate the DataFrames to create the complete table
df_complete = pd.concat([df_assets, df_additional], ignore_index=True)

# Convert numeric columns to float
df_complete['2022'] = pd.to_numeric(df_complete['2022'].str.replace(',', ''), errors='coerce')
df_complete['2021'] = pd.to_numeric(df_complete['2021'].str.replace(',', ''), errors='coerce')


# Print the complete table
print(df_complete)

                                          Category        2022        2021
0                          Cash & cash equivalents   159727124   196276818
1                           Loans to members - net  2006007543  1812554760
2                                Investments - net   436009396   442691070
3                         Share insurance deposits    22404491    21088087
4                       Property & equipment - net    72865806    73988903
5                                     Other assets    67157515    62727010
6                                     Total Assets  2764171874  2609326648
7                                  Members' shares  2367703123  2304469074
8           Accrued expenses and other liabilities    22178627     8813915
9                                   Borrowed funds   152500000    47500000
10                               Total Liabilities  2542381750  2360782989
11                               Retained earnings   273256010   250297815
12   Accumulated other comprehensive income (loss)   -51465887    -1754156
13                           Total Members’ Equity   221790124   248543659
14           Total Liabilities and Members’ Equity  2764171874  2609326648
15                               Interest on loans    82655221    68828526
16    Interest on investments and cash equivalents    10668145     7253814
17                           Total Interest Income    93323366    76082340
18                    Dividends on members' shares    -3089566    -2986948
19                      Interest on borrowed funds    -2177786     -402858
20                          Total Interest Expense    -5267352    -3389806
21                             Net Interest Income    88056013    72692534
22                       Provision for Loan Losses     8230118     1573648
23             Net Interest Income After Provision    79825895    71118886
24                  Service charges and other fees    12386604    11937739
25                       Other non-interest income    21115956    20000467
26  Gain (loss) on sales of property and equipment     5449153      967057
27              Gain (loss) on sale of investments    -5758275      990818
28                       Total Non-Interest Income    33193438    33896081
29                           Salaries and benefits   -44500571   -40396930
30                                      Operations   -39868778   -33713380
31                                       Occupancy    -5691789    -5276312
32       Total General and Administrative Expenses   -90061138   -79386622